title: "alexwlchan’s notebook"
email: "alex@alexwlchan.net"
url: "https://notebook.alexwlchan.net"

source: "src"
destination: "_site"

social:
  github: "alexwlchan"
  twitter: "alexwlchan"
  linode_referral: "ba2e6ce21e0c63952a7c74967ea0b96617bd44a3"

date_format: "%-d %B %Y"

permalink: "/:year/:month/:title/"

liquid:
  error_mode: "strict"

sass:
  sass_dir: "_scss"
  style: "compressed"
